EXP_NAME: BERT
SEED: 223

MODE:
    do_train: False
    do_test: True
    test_list:
        - train
        - validation
        - test

DATASET:
    name: BERT
    data_path: ../data/Part1 # news article directory
    saved_data_path: ../data/Part1/BERT_w512
    PARAMETERS:
        max_word_len: 512

TOKENIZER:
    name: bert

MODEL:
    modelname: bert
    PARAMETERS:
        pretrained_name: 'skt/kobert-base-v1'
        num_classes: 2
    CHECKPOINT:
        checkpoint_path: /saved_model/BERT/best_model.pt

TRAIN:
    batch_size: 64
    num_workers: 12

LOG:
    log_interval: 10

RESULT:
    savedir: '/saved_model/Part1'
    result_name: results
